name: Automação Google Sheets e Drive

on:
  schedule:
    - cron: '0 8 * * *' # Executa todos os dias às 08:00 UTC (ajuste se necessário)
  workflow_dispatch:     # Permite executar manualmente pelo site do GitHub quando quiser

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install requests pandas google-api-python-client google-auth

      - name: Run script
        env:
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }} # <--- Adicione esta linha
        run: python SCRIPT-UPLOAD-HORARIO.py

      - name: Salvar CSV como Artifact
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-notion
          path: log_execucao.csv



